name: Pages Publish

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  # [pull_request_target]
  push:
    branches: [ master, main ]
    paths:
      - 'docs/*'
      - 'themes/*'
      - 'docs/modelldokumentation/*'
      - 'docs/erfassungsrichtlinien/*'
      - 'docs/img/*'
      - 'index.html'
  pull_request:
    branches: [ master, main ]
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions: 
      contents: write
      pull-requests: write
      pages: write
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2 # Stelle sicher, dass die Version kompatibel ist
          #bundler-cache: true # Automatisch 'bundle install' ausf√ºhren und Gems cachen
      
      - name: Verify Installation
        run: gem install asciidoctor
      - name: Verify Installation
        run: asciidoctor --version
      - name: create file
        run: |
          asciidoctor -a stylesdir=https://ch-sz-geo.github.io/A000_defaultDesigne/themes/ -a stylesheet=stylesheet.css -a linkcss -o ./docs/modelldokumentation.html ./docs/modelldokumentation/modelldokumentation.adoc
          asciidoctor -a stylesdir=https://ch-sz-geo.github.io/A000_defaultDesigne/themes/ -a stylesheet=style_entry.css -a linkcss -o ./docs/erfassungsrichtlinien.html ./docs/erfassungsrichtlinien/erfassungsrichtlinien.adoc
      - name: install Asciidoc Pdf
        run: gem install asciidoctor-pdf
      - name: create pdfs
        run: |
          curl -fsSL https://ch-sz-geo.github.io/A000_defaultDesigne/themes/pdfTheme.yml -o /tmp/pdfTheme.yml
          curl -fsSL https://github.com/ch-sz-geo/A000_defaultDesigne/raw/refs/heads/main/fonts/tradegothic-Italic.ttf -o /tmp/tradegothic-Italic.ttf
          curl -fsSL https://github.com/ch-sz-geo/A000_defaultDesigne/raw/refs/heads/main/fonts/tradegothic-bold.ttf -o /tmp/tradegothic-bold.ttf
          curl -fsSL https://github.com/ch-sz-geo/A000_defaultDesigne/raw/refs/heads/main/fonts/tradegothic-bold_italic.ttf -o /tmp/tradegothic-bold_italic.ttf
          curl -fsSL https://github.com/ch-sz-geo/A000_defaultDesigne/raw/refs/heads/main/fonts/tradegothic-light.ttf -o /tmp/tradegothic-light.ttf
          curl -fsSL https://github.com/ch-sz-geo/A000_defaultDesigne/raw/refs/heads/main/fonts/tradegothic-normal.ttf -o /tmp/tradegothic-normal.ttf
          asciidoctor-pdf -a allow-uri-read -a imagesdir= -a pdf-fontsdir=/tmp --theme /tmp/pdfTheme.yml -o ./docs/modelldokumentation.pdf ./docs/modelldokumentation/modelldokumentation.adoc
          asciidoctor-pdf -a allow-uri-read -a imagesdir= -a pdf-fontsdir=/tmp --theme /tmp/pdfTheme.yml -o ./docs/erfassungsrichtlinien.pdf ./docs/erfassungsrichtlinien/erfassungsrichtlinien.adoc
      - name: Commit HTML
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Action"
          git add .
          git diff-index --quiet HEAD || git commit -m "Generate HTML from AsciiDoc" && git push
